# Generated by Django 4.2.6 on 2023-10-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_listregsubject_customuser_regsubject_set'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='listregsubject',
            constraint=models.UniqueConstraint(fields=('user', 'subject'), name='unique_user_subject'),
        ),
    ]
