# Generated by Django 4.2.6 on 2023-10-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_listregsubject_unique_user_subject'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listregsubject',
            name='unique_user_subject',
        ),
        migrations.RenameField(
            model_name='listregsubject',
            old_name='subject',
            new_name='Subject',
        ),
        migrations.AddConstraint(
            model_name='listregsubject',
            constraint=models.UniqueConstraint(fields=('user', 'Subject'), name='unique_user_subject'),
        ),
    ]
