# Generated by Django 4.2.6 on 2023-10-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_listregsubject_unique_user_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='RegSubject_set',
        ),
    ]
