# Generated by Django 4.2.6 on 2023-10-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_subject_is_open'),
        ('users', '0005_remove_customuser_regsubject_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='RegSubject_set',
            field=models.ManyToManyField(related_name='StudentReg_set', through='users.ListRegSubject', to='subjects.subject'),
        ),
    ]
