# Generated by Django 4.2.5 on 2023-10-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_regsubject_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='additional_info',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
