# Generated by Django 4.2.6 on 2023-10-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_additional_info_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='additional_info',
        ),
    ]
