# Generated by Django 4.2.6 on 2023-10-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_subject_is_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='sec_subject',
            new_name='subjectID',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='N_subject',
            new_name='subjectName',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='is_open',
            new_name='subjectStatus',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='subject',
            name='term',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
