# Generated by Django 4.2.6 on 2023-10-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_rename_sec_subject_subject_subjectid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subjectID',
            field=models.CharField(max_length=6),
        ),
    ]
